# Generated by Django 6.0.1 on 2026-01-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
            ],
        ),
    ]
