# Generated by Django 6.0.1 on 2026-07-02 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Milk Combo Offer', max_length=100)),
                ('promo_type', models.CharField(choices=[('QTY_DISCOUNT', 'Quantity Threshold Discount (e.g., Buy 3 for Ksh X)'), ('BOGO', 'Buy One Get One Free / Multi-Buy Freebie')], default='QTY_DISCOUNT', max_length=20)),
                ('required_qty', models.IntegerField(help_text='Quantity needed to trigger the promotion (e.g., 3)')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total special price for the bundle (e.g., if 1 is Ksh 60, 3 could be bundle price of Ksh 160)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='inventory.product')),
            ],
        ),
    ]
