# Generated by Django 6.0.1 on 2026-07-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_weighed',
            field=models.BooleanField(default=False, help_text='Check this if the item is loose produce/meat processed via weighing scale barcodes'),
        ),
    ]
