# Generated by Django 6.0.1 on 2026-01-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_identifier', models.CharField(help_text='Phone number or Card ending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_reference', models.CharField(help_text='M-Pesa Receipt Number', max_length=50, unique=True)),
                ('is_assigned', models.BooleanField(default=False, help_text='Flag to prevent reusing the same payment')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Payment',
                'verbose_name_plural': 'M-Pesa Payments',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('CARD', 'Credit/Debit Card')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
