# Generated by Django 6.0.1 on 2026-07-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_mpesapayment_sale_payment_method_sale_reference_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReport',
            fields=[
            ],
            options={
                'verbose_name': '📊 Sales Summary Report',
                'verbose_name_plural': '📊 Sales Summary Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.sale',),
        ),
    ]
