# Generated by Django 6.0.1 on 2026-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Format: 2547XXXXXXXX', max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('points_balance', models.IntegerField(default=0, help_text='Total available spendable reward points balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🏅 Loyalty Member',
                'verbose_name_plural': '🏅 Loyalty Members',
            },
        ),
    ]
