# Generated by Django 6.0.1 on 2026-07-02 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_loyaltyprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_float', models.DecimalField(decimal_places=2, help_text='Starting drawer balance', max_digits=10)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('counted_mpesa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('counted_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '🔑 Till Shift Audit',
                'verbose_name_plural': '🔑 Till Shift Audits',
            },
        ),
    ]
