# Generated by Django 6.0.1 on 2026-07-02 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_cashiershift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='audit_status',
            field=models.CharField(choices=[('CLOSED', 'Closed & Locked'), ('APPROVED', 'Audited & Approved'), ('DISCREPANCY', 'Flagged Discrepancy Investigation')], db_index=True, default='CLOSED', max_length=20),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='manager_notes',
            field=models.TextField(blank=True, help_text='Supervisor review logs, reason for shortages, etc.', null=True),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
