# Generated by Django 6.0.1 on 2026-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_cashiershift_audit_status_cashiershift_audited_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashiershift',
            options={'verbose_name': '🏪 Till Shift Audit', 'verbose_name_plural': '🏪 Till Shift Audits'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprofile',
            options={'verbose_name': '💳 Loyalty Member', 'verbose_name_plural': '💳 Loyalty Members'},
        ),
        migrations.AddField(
            model_name='sale',
            name='kra_control_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='kra_qr_code_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_breakdown_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='manager_notes',
            field=models.TextField(blank=True, help_text='Supervisor review logs, shortages reason, etc.', null=True),
        ),
    ]
